apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: presys
  namespace: {{namespace}}
  labels:
    team: teampeon
spec:
  image: repo.adeo.no:5443/presys:{{version}}
  port: 8080
  ingresses:
    - {{ingress}}
  liveness:
    path: isAlive
    initialDelay: 60
    periodSeconds: 10
    failureThreshold: 20
  readiness:
    path: isReady
    initialDelay: 60
    periodSeconds: 10
    failureThreshold: 20
  vault:
    enabled: true
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      cpu: 1000m
      memory: 768Mi
    requests:
      cpu: 100m
      memory: 512Mi
  prometheus:
    enabled: true
